import { SITE } from "./site";

/** Home-page title. Brand first so the "fortesa" query shows the name, then the core keywords. */
export const DEFAULT_TITLE = "Fortesa | Kamera Sigurie, Alarme & Instalime Elektrike në Shqipëri";

export const DEFAULT_DESCRIPTION =
  "Fortesa (fortesa.al), Tiranë: kamera sigurie, alarme, instalime elektrike, GPS, tra parkimi, porta automatike dhe zgjidhje për hotele. Montim, monitorim 24/7, mirëmbajtje.";

export const SEO_KEYWORDS = [
  "Fortesa",
  "Fortesa Albania",
  "fortesa.al",
  "kamera sigurie",
  "kamera sigurie Tiranë",
  "CCTV Tiranë",
  "sisteme alarmi",
  "alarme shtëpie",
  "instalime elektrike",
  "elektricist Tiranë",
  "GPS për makina",
  "gjurmim GPS",
  "tra parkimi",
  "tra automatik",
  "sisteme parkingu",
  "porta automatike",
  "motor porte",
  "detektim zjarri",
  "detektor tymi",
  "brava elektronike hoteli",
  "kontroll aksesi",
  "rrjete Wi-Fi",
  "kabllim strukturuar",
  "telefoni VoIP hotel",
  "sisteme audio",
  "muzikë sfondi",
  "siguri Tiranë",
  "Shqipëri",
];

/** The share image generated by app/opengraph-image.js, resolved against metadataBase. */
export const OG_IMAGE = { url: "/opengraph-image", width: 1200, height: 630, alt: "Fortesa, Siguri dhe Teknologji" };

/**
 * Open Graph fields shared by every page. Next does not deep-merge nested
 * metadata objects, so a page that sets openGraph must spread this (images included).
 */
export const OG_BASE = {
  type: "website",
  locale: "sq_AL",
  siteName: SITE.name,
  images: [OG_IMAGE],
};

/**
 * Metadata for one page: title (the layout template appends "| Fortesa"),
 * description, canonical URL and matching Open Graph / Twitter tags.
 */
export function pageMetadata({ title, description = DEFAULT_DESCRIPTION, path = "/" }) {
  const fullTitle = title ? `${title} | ${SITE.name}` : DEFAULT_TITLE;
  return {
    ...(title ? { title } : {}),
    description,
    alternates: { canonical: path },
    openGraph: { ...OG_BASE, title: fullTitle, description, url: path },
    twitter: { card: "summary_large_image", title: fullTitle, description, images: [OG_IMAGE.url] },
  };
}
